# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-09 10:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='product_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
