# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-10 06:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_inventory_product_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='operation',
            field=models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], default='create', max_length=30),
        ),
    ]
