# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-13 20:03
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_auto_20190311_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
