# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-03-14 14:55
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0014_auto_20190314_0253'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='role',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
